spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://root:pass123@localhost:27017/fitnessactivity?authSource=admin
      database: fitnessactivity



server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/